---
- name: Install required system packages
  apt: name={{ item }} state=present update_cache=yes
  loop:
    - 'python3-pip'

- name: Install Docker Module for Python
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose
  